version: '3'

services:

  nginx:
    build: 
      context: nginx
    container_name: nginx
    networks:
      - node-network
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
      - app

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    tty: true
    volumes:
    - ./node:/usr/src/app
    command: ["node", "index.js"]
    networks:
      - node-network
    depends_on:
      - db
      
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./people.sql:/docker-entrypoint-initdb.d/people.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge 